# frozen_string_literal: true

source "https://rubygems.org"

gem "star_server", path: "../../star_server"
gem "star_adapter_mongodb", path: "../../star_adapter_mongodb"
gem "star_adapter_sqlite", path: "../../star_adapter_sqlite"

gem "base64", "~> 0.2.0"
gem "dotenv", "~> 3.1"
gem "scrypt", "~> 3.0"
