#!/usr/bin/env ruby

require "securerandom"
require "./lib/database_adapter/sqlite"

app unhype

db Star::DatabaseAdapter::Sqlite

model(tasklists) {
  id { string { SecureRandom.uuid } }
  name { required string }
}

model(tasks) {
  id { string { SecureRandom.uuid } }
  title { required string }
  tasklist_id { required string }
  created_at { date { DateTime.now } }
  date_due { date { DateTime.now } }
  closed_at { date }
}

router {
  before {
    puts "#{request.method} #{request.uri}"
  }

  tasklists {
    get {
      use {
        query {
          name { string }
        }
      }

      app.models.tasklists.where(name:).to_json
    }

    post {
      use {
        body {
          name { required string }
        }
      }

      app.models.tasklists.create(name:).to_json
    }

    scope("{tasklist_id}") {
      get {
        app.models.tasklists.find(id: tasklist_id).to_json
      }

      patch {
        use {
          body {
            name { string }
          }
        }

        app.models.tasklists.update(match: {id: tasklist_id}, update: {name:})
      }

      delete {
        app.models.tasklists.delete(id: tasklist_id)
      }

      tasks {
        get {
          app.models.tasks.where(tasklist_id:).to_json
        }

        post {
          use {
            body {
              title { required string }
              date_due { date { DateTime.now } }
            }
          }

          app.models.tasks.create(tasklist_id:, title:, date_due:).to_json
        }

        scope("{task_id}") {
          get {
            app.models.tasks.find(tasklist_id:, id: task_id).to_json
          }

          patch {
            use {
              body {
                title { string }
                date_due { date }
                closed_at { date }
              }
            }

            update = {title:, date_due:, closed_at:}.filter { |k, v| !v.nil? }.to_h
            app.models.tasks.update(match: {tasklist_id:, id: task_id}, update:).to_json
          }

          delete {
            app.models.tasks.delete(tasklist_id:, id: task_id).to_json
          }
        }
      }
    }
  }
}
