#!/usr/bin/env ruby

require "./lib/database_adapter/json"

app unhype

db Star::DatabaseAdapter::Json

model(tasks) {
  title { required string }
  created_at { date { DateTime.now } }
  date_due { date { DateTime.now } }
}

main {
  models.tasks.update(match: {title: "foobar"}, update: {title: "baz"})

  models.tasks.create title: "foobar"

  puts app.models.tasks.where(title: "foobar").to_json
}
