#!/usr/bin/env ruby

require "./lib/database_adapter/json"

app unhype

db Star::DatabaseAdapter::Json

model(tasks) {
  title { required string }
  created_at { date { DateTime.now } }
  date_due { date { DateTime.now } }
}

router {
  get("/") {
    use {
      query {
        title String
      }
    }

    app.models.tasks.where(title:).to_json
  }

  post("/") {
    use {
      body {
        title String
      }
    }

    app.models.tasks.create(title:).to_json
  }
}

main {
  app.serve!
}
